---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      bun:
        patterns:
          - "github.com/uptrace/bun"
          - "github.com/uptrace/bun/*"
