---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "node"
        versions: [ "21.x", "23.x", "25.x" ] # 奇数バージョンは開発版なので無視する
